### ISSUE TITLE
emailFailReport.py contacts localhost regardless of EMAIL_HOST env setting

### ISSUE THREAD

**Issue by lwo** [artefactual/archivematica#794]
Issue #624 describes the reason to use the django.core.mail package. 

In our latest qa/1.x installation which uses this package, the EMAIL_HOST environmental variable is set with the ansible-archivamatica-src playbook in all three (archivematica-dashboard, archivematica-mcp-server and archivematica-mcp client) configuration files.

However, when emailFailReport.py is invoked it still contacts localhost... Did we overlook something?

**Comment by sevein** [comment]
@lwo we don't have env lookups in place yet so it's just relying on defaults. This has been solved in JiscRDSS but it hasn't been ported yet. I'm not sure if it'll happen in time for 1.7 - we're pretty much in feature freeze AFAIK.

You can find at https://docs.djangoproject.com/en/1.8/topics/email/ all the settings that you can tweak. I believe your only option at the moment is to edit the [MCPClient settings](https://github.com/artefactual/archivematica/blob/qa/1.x/src/MCPClient/lib/settings/common.py) file manually. It's here:

**Comment by sevein** [comment]
This is the work we did in the JiscRDSS fork:
- https://github.com/JiscRDSS/archivematica-storage-service/pull/18
- https://github.com/JiscRDSS/archivematica/pull/35

**Comment by lwo** [comment]
Yes, those settings from the JiskRDSS for work over at our end. I'll make a fork from qa/1.x\1.7 with this tweak till this functionality is ported in...

**Comment by ross-spencer** [comment]
@sevein should this issue still be open for a future release?

**Comment by sevein** [comment]
Yes, agree. Also, this is related: https://github.com/artefactual/archivematica/pull/813.

**Comment by sevein** [comment]
Fixed by #813.
